import './globals.css'
import { Atkinson_Hyperlegible } from 'next/font/google'

const font = Atkinson_Hyperlegible({weight: "400", style: "italic", subsets: ["latin"]})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <nav>Root Navbar</nav>
        {children}
        </body>
    </html>
  )
}
